---
name: Linting
on: push
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: ./.github/workflows/install-py.yml
      - name: Lint
        uses: super-linter/super-linter@v6.7.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
