---
name: Tests
on: push
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: ./.github/actions/install-py.yml
      - name: Run tests
        run: pytest
