---
name: Tests
on: push
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: ./.github/workflows/install-py.yml
      - name: Run tests
        run: pytest
